[package]
name = "pulsar"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
device_query = "2.1.0"
lazy_static = "1.5.0"
parking_lot = { version = "0.12.3", features = ["arc_lock"] }
rand = "0.8.5"
rodio = "0.19.0"
wide = "0.7.28"
